name: publish
on: [workflow_dispatch]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PUBLISH_TOKEN }}
      - name: Build Docker image
        run: |
          docker build . --tag 'ghcr.io/${{ github.repository }}:latest'
          docker push 'ghcr.io/${{ github.repository }}:latest'
